### ISSUE TITLE
Plugin should not be order dependent

### ISSUE THREAD

**Issue by ben-manes** [marcingrzejszczak/gradle-test-profiler#39]
If the plugin is applied prior to the `java` plugin the build fails because the `test` task has not yet been added. This can be resolved by using `afterEvaluate` to complete at the end of the configuration phase.

```
Caused by: org.gradle.api.UnknownTaskException: Task with name 'test' not found in project ':caffeine'.
    at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:85)
    at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:192)
    at org.gradle.api.internal.tasks.DefaultTaskCollection.getByName(DefaultTaskCollection.java:34)
    at org.gradle.api.tasks.TaskCollection$getByName$0.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at com.blogspot.toomuchcoding.testprofiler.BuildBreaker.createAfterCompilationTestTaskModifier(BuildBreaker.groovy:34)
    at com.blogspot.toomuchcoding.testprofiler.BuildBreaker.performBuildBreakingLogic(BuildBreaker.groovy:27)
    at com.blogspot.toomuchcoding.testprofiler.TestProfilerPlugin.performBuildBreakingLogic(TestProfilerPlugin.groovy:76)
    at com.blogspot.toomuchcoding.testprofiler.TestProfilerPlugin.apply(TestProfilerPlugin.groovy:48)
    at com.blogspot.toomuchcoding.testprofiler.TestProfilerPlugin.apply(TestProfilerPlugin.groovy)
```

**Comment by marcingrzejszczak** [comment]
Fixed in 0.3.1 ! Thanks :)

**Comment by snekse** [comment]
I seem to be getting the reverse problem.
`Task 'profileTests' not found in project`

I would have thought that applying both the Java plugin and this plugin would be enough to have the task defined.  Any thoughts?

**Comment by marcingrzejszczak** [comment]
Can you show me your sample application? Do you have the code somewhere?

**Comment by snekse** [comment]
I'll try to get a sample app going, but it's fairly straight forward.  It's a multi-module app if that matters.

**Comment by marcingrzejszczak** [comment]
THat's too little information cause I've successfully applied the plugin to a gigantic multi-module app. So with the sample app I'll be able to debug the issue.
